import NavBar from '@/components/NavBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  {'name': 'Dashboard', 'href': '/dashboard'},
  {'name': 'About', 'href': '/about'},
  {'name': 'Movies', 'href': '/movies'},
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar links={links}/>
        <div className='container mx-auto bg-slate-100 py-10 px-5'>{children}</div>
        </body>
    </html>
  )
}
